version: '3.8'
services:
  database:
    image: mongo:latest
    container_name: cms_mongoAtlas_db
    
    # ports:
    #   - 27019:27017
    volumes:
      - cms_mongoAtlas_data:/data/db
    networks:
      - backend_network
  backend:
    build: ./backend_cms_doc_time
    container_name: backend_cms_doc_time
    ports:
      - $BACKENDPORT:3000
    volumes:
      - ./backend_cms_doc_time:/app
    networks:
      - backend_network
      - frontend_network
    depends_on:
      - database
  frontend:
    build: ./frontend_cms_doc_time
    container_name: frontend_cms_doc_time
    ports:
      - $FRONTENDPORT:5173
    volumes:
      - ./frontend_cms_doc_time:/app
    networks:
      - frontend_network

volumes:
  cms_mongoAtlas_data:
networks:
  backend_network:
  frontend_network: